# Auth Service
apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  ports:
  - name: http
    port: 8000
  selector:
    app: codr-user-auth
---
# Auth Config
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-auth-env
data:
  ### KAFKA SETTINGS ###
  KAFKA_CONSUMER_GROUP: codr.user.auth.consumer-group
  ### OPENAPI SETTINGS ###
  OPENAPI_INFO_TITLE: User Auth API
  OPENAPI_INFO_DESC: Codr's authentication service
  # OPENAPI_SERVER_ONE_URL: http://localhost:8000/v1/
  # OPENAPI_SERVER_ONE_DESC: Local server
  OPENAPI_SERVER_TWO_URL: http://api.codr.local/v1/auth/
  OPENAPI_SERVER_TWO_DESC: Dev server
---
# User Auth Deployment
kind: Deployment
apiVersion: apps/v1
metadata:
  name: codr-user-auth
  labels:
    app: codr-user-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codr-user-auth
  template:
    metadata:
      name: codr-user-auth
      labels:
        app: codr-user-auth
    spec:
      containers:
      # RESTful API container
      - name: auth
        # grab the container from the Github container registry
        image: ghcr.io/codrjs/codr-user-auth:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: shared-env
        - configMapRef:
            name: user-auth-env
        - secretRef:
            name: secret-ses
        resources:
          limits:
            memory: 256Mi
            cpu: "0.5"
          requests:
            memory: 128Mi
            cpu: "0.2"
