# Session Service
apiVersion: v1
kind: Service
metadata:
  name: session
spec:
  ports:
  - name: http
    port: 8000
  selector:
    app: codr-user-session
---
# Session Config
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-session-env
data:
  ### KAFKA SETTINGS ###
  KAFKA_CONSUMER_GROUP: codr.user.session.group
  ### OPENAPI SETTINGS ###
  OPENAPI_INFO_TITLE: User Session API
  OPENAPI_INFO_DESC: Preform CRUD operations on the user session collection in Mongo.
  # OPENAPI_SERVER_ONE_URL: http://localhost:8000/v1/
  # OPENAPI_SERVER_ONE_DESC: Local server
  OPENAPI_SERVER_TWO_URL: http://api.codr.local/v1/session/
  OPENAPI_SERVER_TWO_DESC: Dev server
---
# User Session Deployment
kind: Deployment
apiVersion: apps/v1
metadata:
  name: codr-user-session
  labels:
    app: codr-user-session
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codr-user-session
  template:
    metadata:
      name: codr-user-session
      labels:
        app: codr-user-session
    spec:
      containers:
      # RESTful API container
      - name: session
        # grab the container from the Github container registry
        image: ghcr.io/codrjs/codr-user-session:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: shared-env
        - configMapRef:
            name: user-session-env
        resources:
          limits:
            memory: 256Mi
            cpu: "0.5"
          requests:
            memory: 128Mi
            cpu: "0.2"
