# User Service
apiVersion: v1
kind: Service
metadata:
  name: user
spec:
  ports:
  - name: http
    port: 8000
  selector:
    app: codr-user-entity
---
# User Config
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-entity-env
data:
  ### KAFKA SETTINGS ###
  KAFKA_CONSUMER_GROUP: codr.user.entity.group
  ### OPENAPI SETTINGS ###
  OPENAPI_INFO_TITLE: User Entity API
  OPENAPI_INFO_DESC: Preform CRUD operations on the user collection in Mongo.
  # OPENAPI_SERVER_ONE_URL: http://localhost:8000/v1/
  # OPENAPI_SERVER_ONE_DESC: Local server
  OPENAPI_SERVER_TWO_URL: http://api.codr.local/v1/user/
  OPENAPI_SERVER_TWO_DESC: Dev server
---
# User Entity Deployment
kind: Deployment
apiVersion: apps/v1
metadata:
  name: codr-user-entity
  labels:
    app: codr-user-entity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codr-user-entity
  template:
    metadata:
      name: codr-user-entity
      labels:
        app: codr-user-entity
    spec:
      containers:
      # RESTful API container
      - name: user
        # grab the container from the Github container registry
        # image: ghcr.io/codrjs/codr-user-user:latest
        image: ghcr.io/codrjs/codr-user-user:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: shared-env
        - configMapRef:
            name: user-entity-env
        resources:
          limits:
            memory: 256Mi
            cpu: "0.5"
          requests:
            memory: 128Mi
            cpu: "0.2"
