---
# Codr UI Service
apiVersion: v1
kind: Service
metadata:
  name: codr-srv
spec:
  ports:
    - protocol: TCP
      name: http
      port: 3000
  selector:
    app: codr
---
# Codr API Service
apiVersion: v1
kind: Service
metadata:
  name: codr-api-srv
spec:
  ports:
    - protocol: TCP
      name: api
      port: 8000
  selector:
    app: codr
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ui-env
data:
  SECRET: "sessionSecret"
  NEXT_PUBLIC_ORG_NAME: "your org name"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-env
data:
  HOST: "http://yourdomain.tld"
  API_PATH: "/api/v1"
  ADMIN_EMAIL: "yourEmailAddress"
  JWT_ISSUER: "yourdomain.tld"
  JWT_ALGORITHM: "HS256"
  JWT_SECRET: "jwtSignSecret"
  SECRET: "sessionSecret"
  GITHUB_CLIENT_ID: ""
  GITHUB_CLIENT_SECRET: ""
  EMAIL_FROM: "'Your Team' <noreply@yourdomain.tld>"
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
---
# Codr Deployment
kind: Deployment
apiVersion: apps/v1
metadata:
  name: codr
  labels:
    app: codr
spec:
  replicas: 3
  selector:
    matchLabels:
      app: codr
  template:
    metadata:
      labels:
        app: codr
    spec:
      containers:
        # Web client container
        - name: codr-ui
          # grab the container from the Github container registry
          image: ghcr.io/codrjs/webui:latest
          imagePullPolicy: "Always"
          ports:
            - name: http
              containerPort: 3000
          envFrom:
            - configMapRef:
                name: ui-env
          env:
            - name: NODE_ENV
              value: production
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
        # RESTful API container
        - name: codr-api
          # grab the container from the Github container registry
          image: ghcr.io/codrjs/api:latest
          imagePullPolicy: "Always"
          ports:
            - name: api
              containerPort: 8000
          envFrom:
            - configMapRef:
                name: api-env
          env:
            - name: NODE_ENV
              value: production
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-codr-admin
                  key: connectionString.standardSrv
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
