---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb
spec:
  members: 3
  type: ReplicaSet
  version: "4.2.6"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: admin
      db: codr
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: admin-password
      roles:
        - name: readWrite
          db: codr
        - name: clusterAdmin
          db: codr
        - name: userAdminAnyDatabase
          db: codr
      scramCredentialsSecretName: codr-scram
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
