# Codr UI Service
apiVersion: v1
kind: Service
metadata:
  name: client-design
spec:
  ports:
  - protocol: TCP
    name: http
    port: 80
  selector:
    app: codr-client-design
---
# Codr Design Deployment
kind: Deployment
apiVersion: apps/v1
metadata:
  name: codr-client-design
  labels:
    app: codr-client-design
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codr-client-design
  template:
    metadata:
      name: codr-client-design
      labels:
        app: codr-client-design
    spec:
      containers:
      # Web design container
      - name: codr-client-design
        # grab the container from the Github container registry
        image: ghcr.io/codrjs/design-library:latest
        imagePullPolicy: "Always"
        ports:
        - name: http
          containerPort: 80
        resources:
          limits:
            memory: 128Mi
            cpu: "0.5"
          requests:
            memory: 64Mi
            cpu: "0.2"
