# Codr UI Service
apiVersion: v1
kind: Service
metadata:
  name: client-docs
spec:
  ports:
  - protocol: TCP
    name: http
    port: 3000
  selector:
    app: codr-client-docs
---
# Codr Deployment
kind: Deployment
apiVersion: apps/v1
metadata:
  name: codr-client-docs
  labels:
    app: codr-client-docs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codr-client-docs
  template:
    metadata:
      name: codr-client-docs
      labels:
        app: codr-client-docs
    spec:
      imagePullSecrets:
      - name: secret-docker
      containers:
      # Web docs container
      - name: codr-client-docs
        # grab the container from the Github container registry
        # image: ghcr.io/codrjs/codr-client-docs:latest
        image: ghcr.io/codrjs/docs:latest
        imagePullPolicy: "Always"
        ports:
        - name: http
          containerPort: 3000
        env:
        - name: NODE_ENV
          value: production
        resources:
          limits:
            memory: 256Mi
            cpu: "0.5"
          requests:
            memory: 64Mi
            cpu: "0.2"
