# Codr Gateway
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  ports:
  - name: http
    port: 80
  selector:
    app: codr-gateway
---
# Codr Deployment
kind: Deployment
apiVersion: apps/v1
metadata:
  name: codr-gateway
  labels:
    app: codr-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codr-gateway
  template:
    metadata:
      name: codr-gateway
      labels:
        app: codr-gateway
    spec:
      containers:
      # RESTful API container
      - name: gateway
        # grab the container from the Github container registry
        # image: ghcr.io/codrjs/codr-gateway:latest
        image: codr-gateway:latest
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 80
        env:
        - name: NAMESPACE
          value: codr-dev
        resources:
          limits:
            memory: 128Mi
            cpu: "1"
          requests:
            memory: 64Mi
            cpu: "0.2"
